module.exports.sentences = [
  "There have been days when I wished to be separated from my body, but today wasn't one of those days.",
  "It was her first experience training a rainbow unicorn.",
  "His ultimate dream fantasy consisted of being content and sleeping eight hours in a row.",
  "Situps are a terrible way to end your day.",
  "It's important to remember to be aware of rampaging grizzly bears.",
  "The opportunity of a lifetime passed before him as he tried to decide between a cone or a cup.",
  "Just go ahead and press that button.",
  "They say that dogs are man's best friend, but this cat was setting out to sabotage that theory.",
  "The miniature pet elephant became the envy of the neighborhood.",
  "After coating myself in vegetable oil I found my success rate skyrocketed.",
  "The fence was confused about whether it was supposed to keep things in or keep things out.",
  "As he waited for the shower to warm, he noticed that he could hear water change temperature.",
  "He always wore his sunglasses at night.",
  "Best friends are like old tomatoes and shoelaces.",
  "Hang on, my kittens are scratching at the bathtub and they'll upset by the lack of biscuits.",
  "Someone I know recently combined Maple Syrup & buttered Popcorn thinking it would taste like caramel popcorn. It didn't and they don't recommend anyone else do it either.",
  "She had a difficult time owning up to her own crazy self.",
  "Don't piss in my garden and tell me you're trying to help my plants grow.",
  "The father died during childbirth.",
  "Pair your designer cowboy hat with scuba gear for a memorable occasion.",
  "He liked to play with words in the bathtub.",
  "He embraced his new life as an eggplant.",
  "I love bacon, beer, birds, and baboons.",
  "The quick brown fox jumps over the lazy dog.",
  "I never knew what hardship looked like until it started raining bowling balls.",
  "Sometimes, all you need to do is completely make an ass of yourself and laugh it off to realize that life isn't so bad after all.",
  "Art doesn't have to be intentional.",
  "The minute she landed she understood the reason this was a fly-over state.",
  "Being unacquainted with the chief raccoon was harming his prospects for promotion.",
  "Peanut butter and jelly caused the elderly lady to think about her past.",
  "Purple is the best city in the forest.",
  "The efficiency with which he paired the socks in the drawer was quite admirable.",
  "Always bring cinnamon buns on a deep-sea diving expedition.",
  "The skeleton had skeletons of his own in the closet.",
  "The glacier came alive as the climbers hiked closer.",
  "Her daily goal was to improve on yesterday.",
  "A glittering gem is not enough.",
  "The rusty nail stood erect, angled at a 45-degree angle, just waiting for the perfect barefoot to come along.",
  "The gloves protect my feet from excess work.",
  "She did not cheat on the test, for it was not the right thing to do.",
  "He excelled at firing people nicely.",
  "This is the last random sentence I will be writing and I am going to stop mid-sent",
  "You bite up because of your lower jaw.",
  "The fifty mannequin heads floating in the pool kind of freaked them out.",
  "There's no reason a hula hoop can't also be a circus ring.",
  "There was no ice cream in the freezer, nor did they have money to go to the store.",
  "He wasn't bitter that she had moved on but from the radish.",
  "When money was tight, he'd get his lunch money from the local wishing well.",
  "For oil spots on the floor, nothing beats parking a motorbike in the lounge.",
  "He didn't understand why the bird wanted to ride the bicycle.",
  "I never knew what hardship looked like until it started raining bowling balls.",
  "It took him a month to finish the meal.",
  "He set out for a short walk, but now all he could see were mangroves and water were for miles.",
  "The memory we used to share is no longer coherent.",
  "He swore he just saw his sushi move.",
  "It would have been a better night if the guys next to us weren't in the splash zone.",
  "The murder hornet was disappointed by the preconceived ideas people had of him.",
  "Random words in front of other random words create a random sentence.",
  "The fifty mannequin heads floating in the pool kind of freaked them out.",
  "The elderly neighborhood became enraged over the coyotes who had been blamed for the poodle's disappearance.",
  "She was amazed by the large chunks of ice washing up on the beach.",
  "When nobody is around, the trees gossip about the people who have walked under them.",
  "The small white buoys marked the location of hundreds of crab pots.",
  "The swirled lollipop had issues with the pop rock candy.",
  "I love bacon, beer, birds, and baboons.",
  "Don't step on the broken glass.",
  "The overpass went under the highway and into a secret world.",
  "I've never seen a more beautiful brandy glass filled with wine.",
  "He had concluded that pigs must be able to fly in Hog Heaven.",
  "He drank life before spitting it out.",
  "100 years old is such a young age if you happen to be a bristlecone pine.",
  "Having no hair made him look even hairier.",
  "She couldn't understand why nobody else could see that the sky is full of cotton candy.",
  "If you like tuna and tomato sauce, try combining the two, it's really not as bad as it sounds.",
  "The tart lemonade quenched her thirst, but not her longing.",
  "That is an appealing treasure map that I can't read.",
  "I'm a living furnace.",
  "It's always a good idea to seek shelter from the evil gaze of the sun.",
  "Nothing seemed out of place except the washing machine in the bar.",
  "Don't put peanut butter on the dog's nose.",
  "As he waited for the shower to warm, he noticed that he could hear water change temperature.",
  "Even with the snow falling outside, she felt it appropriate to wear her bikini.",
  "The shark-infested South Pine channel was the only way in or out.",
  "They ran around the corner to find that they had traveled back in time.",
  "He's in a boy band which doesn't make much sense for a snake.",
  "I think I will buy the red car, or I will lease the blue one.",
  "I liked their first two albums but changed my mind after that charity gig.",
  "25 years later, she still regretted that specific moment.",
  "There are no heroes in a punk rock band.",
  "The best part of marriage is animal crackers with peanut butter.",
  "Mr. Montoya knows the way to the bakery even though he's never been there.",
  "This book is sure to liquefy your brain.",
  "The fog was so dense even a laser decided it wasn't worth the effort.",
  "I love eating toasted cheese and tuna sandwiches.",
  "He invested some skill points in Charisma and Strength.",
  "his seven-layer cake only had six layers.",
  "He knew it was going to be a bad day when he saw mountain lions roaming the streets.",
  "Greetings from the real universe.",
  "Joe made the sugar cookies; Susan decorated them.",
  "The truth is that you pay for your lifestyle in hours.",
  "Peanut butter and jelly caused the elderly lady to think about her past.",
  "He was surprised that his immense laziness was inspirational to others.",
  "She had convinced her kids that any mushroom found on the ground would kill them if they touched it.",
  "Potato wedges probably are not best for relationships.",
  "The book is in front of the table.",
  "She wrote him a long letter, but he didn't read it.",
  "Bill ran from the giraffe toward the dolphin.",
  "For the 216th time, he said he would quit drinking soda after this last Coke.",
  "The river stole the gods.",
  "I'm worried by the fact that my daughter looks to the local carpet seller as a role model.",
  "She traveled because it cost the same as therapy and was a lot more enjoyable.",
  "I am counting my calories, yet I really want dessert.",
  "Iron pyrite is the most foolish of all minerals.",
  "He went back to the video to see what had been recorded and was shocked at what he saw.",
  "She couldn't understand why nobody else could see that the sky is full of cotton candy.",
  "He spiked his hair green to support his iguana.",
  "Tomatoes make great weapons when water balloons aren't available.",
  "The furnace repairman indicated the heating system was acting as an air conditioner.",
  "I was offended by the suggestion that my baby brother was a jewel thief.",
  "She folded her handkerchief neatly.",
  "He never understood why what, when, and where left out who.",
  "If you don't like toenails, you probably shouldn't look at your feet.",
  "She only paints with bold colors; she does not like pastels.",
  "I trust everything that's written in purple ink.",
  "She was amazed by the large chunks of ice washing up on the beach.",
  "It would have been a better night if the guys next to us weren't in the splash zone.",
  "I am my aunt's sister's daughter.",
  "The sudden rainstorm washed crocodiles into the ocean.",
  "I liked their first two albums but changed my mind after that charity gig.",
  "Joyce enjoyed eating pancakes with ketchup.",
  "At that moment I was the most fearsome weasel in the entire swamp.",
  "He liked to play with words in the bathtub.",
  "He wasn't bitter that she had moved on but from the radish.",
  "Dolores wouldn't have eaten the meal if she had known what it actually was.",
  "The pet shop stocks everything you need to keep your anaconda happy.",
  "I honestly find her about as intimidating as a basket of kittens.",
  "While all her friends were positive that Mary had a sixth sense, she knew she actually had a seventh sense.",
  "He found his art never progressed when he literally used his sweat and tears.",
  "He drank life before spitting it out.",
  "This made him feel like an old-style root beer float smells.",
  "She was too short to see over the fence.",
  "I don't respect anybody who can't tell the difference between Pepsi and Coke.",
  "Separation anxiety is what happens when you can't find your phone.",
  "He decided that the time had come to be stronger than any of the excuses he'd used until then.",
  "He wondered if it could be called a beach if there was no sand.",
  "I'm working on a sweet potato farm.",
  "I've traveled all around Africa and still haven't found the gnu who stole my scarf.",
  "He quietly entered the museum as the super bowl started.",
  "The random sentence generator generated a random sentence about a random sentence.",
  "The sign said there was road work ahead so he decided to speed up.",
];
